name: Build Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+' # Push events to matching v1.2 tags

permissions:
  contents: write
  packages: write

env:
  VERSION: unset

jobs:
  release-matrics:
    name: Release binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, freebsd, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Set version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Build
      run: go build -a -trimpath -o tdu-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags "-X main.gitTag=${{ env.VERSION }}" .

    - name: Archive
      run: tar -czf tdu-${{ matrix.goos }}-${{ matrix.goarch }}-v${{ env.VERSION }}.tar.gz tdu-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: tdu-${{ matrix.goos }}-${{ matrix.goarch }}-v${{ env.VERSION }}.tar.gz