name: Build Release

on:
  release:
    types: [prereleased]

permissions:
  contents: write
  packages: write

env:
  VERSION: unset
  ARCHIVE: 

jobs:
  release-matrics:
    name: Release binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, freebsd, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: go version

    - name: Set version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Build unix binary
      if: matrix.goos != 'windows'
      run: go build -a -trimpath -o tdu -ldflags "-X main.gitTag=${{ env.VERSION }}" .

    - name: Build windows binary
      if: matrix.goos == 'windows'
      run: go build -a -trimpath -o tdu.exe -ldflags "-X main.gitTag=${{ env.VERSION }}" .

    - name: Create unix tarball
      if: matrix.goos != 'windows'
      env:
        ARCHIVE: tdu-${{ matrix.goos }}-${{ matrix.goarch }}-v${{ env.VERSION }}.tar.gz
      run: tar -czf ${{ env.ARCHIVE }} tdu

    - name: Create windows zip
      if: matrix.goos == 'windows'
      env:
        ARCHIVE: tdu-${{ matrix.goos }}-${{ matrix.goarch }}-v${{ env.VERSION }}.zip
      run: zip ${{ env.ARCHIVE }} tdu.exe

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE }}
        path: ${{ env.ARCHIVE }}